[package]
name = "Prune"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-htslib = "0.40.2"
clap = { version = "4.0.18", features = ["derive"] }